### ISSUE TITLE
图片极智压缩存在问题

### ISSUE THREAD

**Issue by MIKU-N** [sy-records/sync-qcloud-cos#52]
目前的代码中，图片极智压缩/文档处理功能虽然在开启的开关处做了可用区的判断，但看样子似乎进入这个页面时会触发一次
`$bucketname.$domain_type.myqcloud.com`这个拼接，然后这个拼接会触发代码中的这段判断
```
        $domain_type = '.cos.';
        if ($action == 'PutBucketImageStyle' || $action == 'GetBucketImageStyle' || $action == 'DeleteBucketImageStyle'
            || $action == 'PutBucketGuetzli' || $action == 'GetBucketGuetzli' || $action == 'DeleteBucketGuetzli'
            || $action == 'BindCiService' || $action == 'GetCiService' || $action == 'UnBindCiService'
            || $action == 'GetHotLink' || $action == 'AddHotLink'
            || $action == 'OpenOriginProtect' || $action == 'GetOriginProtect' || $action == 'CloseOriginProtect'
            || $action == 'OpenImageSlim' || $action == 'GetImageSlim' || $action == 'CloseImageSlim' ) {
            $domain_type = '.pic.';
        }
```
当我选择的可用区为`全球加速`时
于是乎链接就会变成`$bucketname.pic.accelerate.myqcloud.com`
但是这个拼接域名请求下来是没有解析的
![image](https://github.com/sy-records/sync-qcloud-cos/assets/61493780/5bc18e0b-a902-4308-a8f7-574832b52140)

那么此时极智压缩和文档处理这两个页面都是打不开的，且会触发致命错误

```
Fatal error: Uncaught GuzzleHttp\Exception\ConnectException: cURL error 6: Could not resolve: xxx-xxxxxxxxx.pic.accelerate.myqcloud.com (Domain name not found) 
Fatal error: Uncaught GuzzleHttp\Exception\ConnectException: cURL error 6: Could not resolve: ci.accelerate.myqcloud.com (Domain name not found) 
```
![image](https://github.com/sy-records/sync-qcloud-cos/assets/61493780/393b1a25-9360-4368-aa88-f53d13b33fb5)

附我已安装并启用的插件列表
```
- Gmail SMTP 1.2.3.11 版本 | 作者：[naa986](https://wphowto.net/)
- IndexNow 1.0.1 版本 | 作者：[Microsoft Bing](https://www.bing.com/indexnow)
- Redis Object Cache 2.5.0 版本 | 作者：[Till Krüss](https://objectcache.pro/?ref=oss&utm_source=wp-plugin&utm_medium=author)
- Site Kit by Google 1.114.0 版本 | 作者：[Google](https://opensource.google.com/)
- Sync QCloud COS 2.3.5 版本 | 作者：[沈唁](https://qq52o.me/)
- XML 站点地图 & Google News 5.3.6 版本 | 作者：[RavanH](https://status301.net/)
- 超级缓存 1.11.0 版本 | 作者：[Automattic](https://automattic.com/)
----------------以下为已安装但未启用插件----------------------
- Comment Reply Email 1.0.5 版本 | 作者：[WPJohnny](https://wpjohnny.com/)
- Super Page Cache for Cloudflare 4.7.5 版本 | 作者：[Optimole](https://optimole.com/)
```

**Comment by sy-records** [comment]
调用堆栈别打码，把前面的路径打上就行，我需要看下全部的堆栈

**Comment by MIKU-N** [comment]
> 调用堆栈别打码，把前面的路径打上就行，我需要看下全部的堆栈

![image](https://github.com/sy-records/sync-qcloud-cos/assets/61493780/b4f0c8e0-befd-451a-ad6c-f63f86201288)

```
Fatal error: Uncaught GuzzleHttp\Exception\ConnectException: cURL error 6: Could not resolve: xx-xxxxxxxx.pic.accelerate.myqcloud.com (Domain name not found) (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) in /www/wwwroot/blog.im.ci/wp-content/plugins/sync-qcloud-cos/cos-sdk-v5/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:200 Stack trace: #0 /www/wwwroot/blog.im.ci/wp-content/plugins/sync-qcloud-cos/cos-sdk-v5/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(155): GuzzleHttp\Handler\CurlFactory::createRejection() #1 /www/wwwroot/blog.im.ci/wp-content/plugins/sync-qcloud-cos/cos-sdk-v5/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(105): GuzzleHttp\Handler\CurlFactory::finishError() #2 /www/wwwroot/blog.im.ci/wp-content/plugins/sync-qcloud-cos/cos-sdk-v5/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(198): GuzzleHttp\Handler\CurlFactory::finish() #3 /www/wwwroot/blog.im.ci/wp-content/plugins/sync-qcloud-cos/cos-sdk-v5/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(130): GuzzleHttp\Handler\CurlMultiHandler->processMessages() #4 /www/wwwroot/blog.im.ci/wp-content/plugins/sync-qcloud-cos/cos-sdk-v5/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(145): GuzzleHttp\Handler\CurlMultiHandler->tick() #5 /www/wwwroot/blog.im.ci/wp-content/plugins/sync-qcloud-cos/cos-sdk-v5/vendor/guzzlehttp/promises/src/Promise.php(248): GuzzleHttp\Handler\CurlMultiHandler->execute() #6 /www/wwwroot/blog.im.ci/wp-content/plugins/sync-qcloud-cos/cos-sdk-v5/vendor/guzzlehttp/promises/src/Promise.php(224): GuzzleHttp\Promise\Promise->invokeWaitFn() #7 /www/wwwroot/blog.im.ci/wp-content/plugins/sync-qcloud-cos/cos-sdk-v5/vendor/guzzlehttp/promises/src/Promise.php(269): GuzzleHttp\Promise\Promise->waitIfPending() #8 /www/wwwroot/blog.im.ci/wp-content/plugins/sync-qcloud-cos/cos-sdk-v5/vendor/guzzlehttp/promises/src/Promise.php(226): GuzzleHttp\Promise\Promise->invokeWaitList() #9 /www/wwwroot/blog.im.ci/wp-content/plugins/sync-qcloud-cos/cos-sdk-v5/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending() #10 /www/wwwroot/blog.im.ci/wp-content/plugins/sync-qcloud-cos/cos-sdk-v5/vendor/guzzlehttp/promises/src/Coroutine.php(67): GuzzleHttp\Promise\Promise->wait() #11 /www/wwwroot/blog.im.ci/wp-content/plugins/sync-qcloud-cos/cos-sdk-v5/vendor/guzzlehttp/promises/src/Promise.php(248): GuzzleHttp\Promise\Coroutine->GuzzleHttp\Promise\{closure}() #12 /www/wwwroot/blog.im.ci/wp-content/plugins/sync-qcloud-cos/cos-sdk-v5/vendor/guzzlehttp/promises/src/Promise.php(224): GuzzleHttp\Promise\Promise->invokeWaitFn() #13 /www/wwwroot/blog.im.ci/wp-content/plugins/sync-qcloud-cos/cos-sdk-v5/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending() #14 /www/wwwroot/blog.im.ci/wp-content/plugins/sync-qcloud-cos/cos-sdk-v5/vendor/guzzlehttp/promises/src/Coroutine.php(103): GuzzleHttp\Promise\Promise->wait() #15 /www/wwwroot/blog.im.ci/wp-content/plugins/sync-qcloud-cos/cos-sdk-v5/vendor/guzzlehttp/command/src/ServiceClient.php(77): GuzzleHttp\Promise\Coroutine->wait() #16 /www/wwwroot/blog.im.ci/wp-content/plugins/sync-qcloud-cos/cos-sdk-v5/vendor/guzzlehttp/command/src/ServiceClient.php(153): GuzzleHttp\Command\ServiceClient->execute() #17 /www/wwwroot/blog.im.ci/wp-content/plugins/sync-qcloud-cos/cos-sdk-v5/vendor/qcloud/cos-sdk-v5/src/Client.php(422): GuzzleHttp\Command\ServiceClient->__call() #18 /www/wwwroot/blog.im.ci/wp-content/plugins/sync-qcloud-cos/cos-sdk-v5/src/CI/ImageSlim.php(9): Qcloud\Cos\Client->__call() #19 /www/wwwroot/blog.im.ci/wp-content/plugins/sync-qcloud-cos/sync-qcloud-cos.php(824): SyncQcloudCos\CI\ImageSlim::checkStatus() #20 /www/wwwroot/blog.im.ci/wp-content/plugins/sync-qcloud-cos/sync-qcloud-cos.php(1550): cos_ci_image_slim_page() #21 /www/wwwroot/blog.im.ci/wp-includes/class-wp-hook.php(324): cos_setting_page() #22 /www/wwwroot/blog.im.ci/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters() #23 /www/wwwroot/blog.im.ci/wp-includes/plugin.php(517): WP_Hook->do_action() #24 /www/wwwroot/blog.im.ci/wp-admin/admin.php(259): do_action() #25 /www/wwwroot/blog.im.ci/wp-admin/options-general.php(10): require_once('...') #26 {main} thrown in /www/wwwroot/blog.im.ci/wp-content/plugins/sync-qcloud-cos/cos-sdk-v5/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 200
```

**Comment by sy-records** [comment]
@MIKU-N 修复了，你可以手动更新下代码试试

**Comment by MIKU-N** [comment]
> @MIKU-N 修复了，你可以手动更新下代码试试

没有问题了，建议推一个新的Releases
